apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: community-platform-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SanctuaryV/community-platform-plus-frontend.git
    targetRevision: k8s
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: communities-platform-argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true