apiVersion: v1
kind: Service
metadata:
  name: communities-platform-frontend
  labels:
    app: communities-platform-argo     # ⬅ ให้ตรงกับ Deployment
spec:
  type: LoadBalancer
  selector:
    app: communities-platform-argo     # ⬅ ให้ตรงกัน
  ports:
    - name: http
      port: 80
      targetPort: 80
