apiVersion: v1
kind: Service
metadata:
  name: community-platform-frontend
  labels:
    app: community-platform-frontend
spec:
  type: LoadBalancer
  selector:
    app: community-platform-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
